INSERT into States (name, stateCode)
values ('Alaska', 'AK'),
('Alabama', 'AL'),
('Arizona', 'AZ'),
('Arkansas', 'AR'),
('California', 'CA'),
('Colorado', 'CO')
('Connecticut','CT'),
('Delaware','DE'),
('District of Columbia','DC'),
('Florida','FL',),
('Georgia', 'GA'),
('Hawaii', 'HI'),
('Idaho', 'ID'),
('Illinois', 'IL'),
('Indiana', 'IN'),
('Iowa', 'IA'),
('Kansas','KS'),
('Kentucky','KY'),
('Louisiana','LA'),
('Maine','ME'),
('Maryland','MD'),
('Massachusetts','MA'),
('Michigan','MI'),
('Minnesota','MN'),
('Mississippi','MS'),
('Missouri', 'MO'),
('Montana','MT'),
('Nebraska', 'NE'),
('Nevada','NV'),
('New Hampshire','NH'),
('New Jersey','NJ'),
('New Mexico','NM'),
('New York','NY'),
('North Carolina','NC'),
('North Dakota','ND'),
('Ohio','OH'),
('Oklahoma', 'OK'),
('Oregon','OR'),
('Pennsylvania','PA'),
('Puerto Rico','PR'),
('Rhode Island','RI'),
('South Carolina','SC'),
('South Dakota','SD'),
('Tennessee','TN'),
('Texas','TX'),
('Utah','UT'),
('Vermont','VT'),
('Virginia','VA'),
('Washington','WA'),
('West Virginia','WV'),
('Wisconsin','WI'),
('Wyoming','WY');

INSERT INTO Citizens (first_name, last_name, ssn)
VALUES ('John', 'Smith', '333-00-1111'),
('Jose', 'Sana', '333-00-2222'),
('Moe', 'Wino', '333-00-3333'),
('Nati', 'Moore', '333-00-4444'),
('Andrew', 'Varela', '333-00-5555');

INSERT INTO TownHalls (county)
Values('Los Angeles'),
('San Bernardino'),
('Orange'),
('Alameda')

INSERT INTO DMVs (town, name, time_open, time_close, townHalls_id)
values ('Los Angeles', 'LA DMV', '8:00', '16:00', 1),
('Agoura Hills', 'AH DMV', '8:00', '17:00', 2),
('Los Feliz', 'LF DMV', '8:00', '18:00', 3),
('Pasadena', 'PA DMV', '8:00', '18:00', 3)